### ISSUE TITLE
[setup] Incomplete instructions - github plugin and login needed

### ISSUE THREAD

**Issue by catchSheep** [CurtinIDS/CIDS_Carpentries_Python#1]
## Description
Currently at step 4 in the instructions, "Open Visual Studio Code, navigate to the File Explorer and clone this repository with the following repository name `CurtinIDS/CIDS_Carpentries_Python` into your preferred folder destination"
VS-Code on linux will query for the GitHub plugin, and upon installing it, it will query for a login. The directory does not seem to be able to be cloned without logging in via the plugin using just `CurtinIDS/CIDS_Carpentries_Python`

## Fix
There are two options I see to fix this:
1. Tell the user to insert the full html `https://github.com/CurtinIDS/CIDS_Carpentries_Python.git` or `https://github.com/CurtinIDS/CIDS_Carpentries_Python`
2. Tell the user to install the GitHub plugin and create a github account before cloning
  
Option 1. seems the best to me

**Comment by calvpang** [comment]
Updated README.md.
See 1bd96c2.
