### ISSUE TITLE
[setup] Conda image could be improved

### ISSUE THREAD

**Issue by catchSheep** [CurtinIDS/CIDS_Carpentries_Python#2]
In the setup, at the step telling you to make a new conda env, the explanitory image `assets/vs_code_create_environment.jpg` highlights `venv` instead of `conda`, which could cause someone not paying enough attention \*cough\* to click on `venv`

# Old image
![image](https://github.com/CurtinIDS/CIDS_Carpentries_Python/blob/main/assets/conda_env.jpg?raw=true)

# Suggested new image
![new_image](https://github.com/user-attachments/assets/75072aa1-6715-46bb-a142-1c040cc096c9)
(although my colour scheme is monokai, not sure what the original one is)

**Comment by calvpang** [comment]
Updated README.md.
See 1bd96c2.
