### ISSUE TITLE
[setup] Conda env not auto-selected on pre-existing installation

### ISSUE THREAD

**Issue by catchSheep** [CurtinIDS/CIDS_Carpentries_Python#3]
## Description
Following the steps, at the stage of installing the requirements, the new conda environment is not automatically selected.

## Troubleshooting
On killing a terminal and re-opening it, it appears to manually run the command `conda activate <local conda env path>` a second after opening.
Pressing any key in this time will misform the command, and cause an error (e.g. pressing `p`, the command will become `pconda activate ...` which will error).  
 Alternatively, if ones terminal was already open and in the base environment, no command may be run.

While in the cloned repository directory, running
```
conda activate ./.conda/
```
seems to activate the environment properly
## Suggestions
Possibly have an extra command in the instructions - after opening the terminal with `ctrl+j` have the user run `conda activate ./.conda`. 
- If the environment is not active, it will activate it.
- If the environment is already active, this wont do anything (i.e., the command is safe).

**Comment by calvpang** [comment]
Updated README.md.
See 1bd96c2.
